parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/42.h>"
  zmk_additional_includes:
    - "zmk-helpers/include"


draw_config:
  dark_mode: true
  draw_key_sides: true
  footer_text: ""

